version: "3"
services:
  db:
    build: .
    command: uvicorn backend.sql_app.main:app --host "0.0.0.0" --port "8000"
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
  app:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - db
